### ISSUE TITLE
jtagd randomly segfaults in Socket::Accept()

### ISSUE THREAD

**Issue by azonenberg** [azonenberg/antikernel#2]
<code>
<pre>
Connected to interface "Digilent Adept USB Device A (2232H)" (serial number "210279760222A")

Program received signal SIGSEGV, Segmentation fault.
0x00000000000015e6 in ?? ()
(gdb) bt
#0  0x00000000000015e6 in ?? ()
#1  0x00007ffff7550e74 in Socket::Accept (this=0x611670 <g_socket>) at /tmp/sb0/workdir/src/xptools/Socket.cpp:429
#2  0x000000000040b02e in main (argc=7, argv=0x7fffffffe6e8) at /tmp/sb0/workdir/src/jtagd/main.cpp:269
(gdb) frame 1
#1  0x00007ffff7550e74 in Socket::Accept (this=0x611670 <g_socket>) at /tmp/sb0/workdir/src/xptools/Socket.cpp:429
429	/tmp/sb0/workdir/src/xptools/Socket.cpp: No such file or directory.
(gdb) print this
$1 = (Socket * const) 0x611670 <g_socket>
(gdb) print *this
$2 = {_vptr.Socket = 0x7ffff7751650 <vtable for Socket+16>, m_af = 10, m_type = 1, m_protocol = 6, m_socket = 12}
</pre>
</code>

**Comment by azonenberg** [comment]
==7225== Jump to the invalid address stated on the next line
==7225==    at 0x15E6: ???
==7225==    by 0x40B02D: main (main.cpp:269)
==7225==  Address 0x15e6 is not stack'd, malloc'd or (recently) free'd

**Comment by azonenberg** [comment]
Invalid, not a bug in Antikernel (import table corruption caused by Splash modifying shared libraries on disk, fixed in https://github.com/azonenberg/splash-build-system/commit/cb19c1f274603a0da40469363b7ff6d88c4aa597)
